use borsh::{BorshDeserialize, BorshSerialize};
use solana_program::pubkey::Pubkey;

pub const GAME_TITLE_MAX_LEN: usize = 32;

#[derive(BorshSerialize, BorshDeserialize, Debug, Clone)]
pub struct GameAccountV1 {
    pub is_initialized: bool,
    pub version: u8,
    pub game_title: [u8; GAME_TITLE_MAX_LEN],
    pub owner: Pubkey,
    pub dev_fee_bps: u16,
    pub game_to_protocol_share_bps: u16,
    // -- game_cost was missing
    // -- game_url was missing
    // -- total users was missing
    // -- total_revenue_usd_micro was missing
}

impl GameAccountV1 {
    pub const MAX_SIZE: usize = 1 + 1 + GAME_TITLE_MAX_LEN + 32 + 2 + 2;
}

#[derive(BorshSerialize, BorshDeserialize, Debug, Clone)]
pub struct GameAccount {
    pub is_initialized: bool,
    pub version: u8,
    pub game_title: [u8; GAME_TITLE_MAX_LEN],
    pub owner: Pubkey,
    // The fee the developer charges users
    pub dev_fee_bps: u16,
    // The percentage of the dev fee that goes to the protocol treasury (min 10%)
    pub game_to_protocol_share_bps: u16,
    // The cost in micro_usd to create a User Account, can be 0 for Free to Play games
    pub game_cost: u64, 
    // A URL pointing to the game (e.g. a web2 landing page or a web3 dapp URL), this is optional but can be useful for discovery and analytics
    pub game_url: [u8; 64],
    // Total number of unique users who have created user accounts for this game
    pub total_users: u32,
    // Total revenue in micro_usd generated by this game in game sales, ranked game fees, etc.
    pub total_revenue_usd_micro: u64,
}

impl GameAccount {
    // is_initialized + version + game_title + owner + dev_fee_bps + game_to_protocol_share_bps + game_cost + game_url + total_users + total_revenue_usd_micro = 144 bytes
    pub const MAX_SIZE: usize = 1 + 1 + GAME_TITLE_MAX_LEN + 32 + 2 + 2 + 8 + 64 + 4 + 8;
}